host: "127.0.0.1"
port: 8081

api_dialect: "anthropic"

providers:
  anthropic:
    enabled: true
    # No api_key field here - will use:
    #   1. ANTHROPIC_API_KEY environment variable, OR
    #   2. Client's x-api-key header (passthrough mode)

session_recording:
  enabled: false  # No disk writes

logging:
  level: "debug"
  log_requests: true  # Print to stdout
