# Claude Code Proxy Configuration with Session Recording
# Records all conversations to both JSONL files and SQLite database

host: "127.0.0.1"
port: 8081

# IMPORTANT: Must be "anthropic" for passthrough mode
api_dialect: "anthropic"

providers:
  anthropic:
    enabled: true
    # No api_key field here - will use:
    #   1. ANTHROPIC_API_KEY environment variable, OR
    #   2. Client's x-api-key header (Claude Code provides this)

# Session recording with both JSONL and SQLite
session_recording:
  enabled: true

  # JSONL writer - human-readable session logs
  jsonl:
    enabled: true
    directory: "~/.lunaroute/sessions"
    retention:
      max_age_days: 30  # Keep sessions for 30 days
      max_size_mb: 1024  # Delete oldest when total size exceeds 1GB

  # SQLite writer - queryable session database
  sqlite:
    enabled: true
    path: "~/.lunaroute/sessions.db"
    max_connections: 10

# Track up to 1000 session statistics in memory
session_stats_max_sessions: 1000

logging:
  level: "debug"
  log_requests: true  # See requests in stdout

# Usage with Claude Code:
# 1. Start server: lunaroute-server --config claude-code-proxy-with-recording.yaml
# 2. Set proxy: export ANTHROPIC_BASE_URL=http://localhost:8081
# 3. Run Claude Code normally
#
# Sessions will be recorded to:
# - JSONL: ~/.lunaroute/sessions/YYYY-MM-DD/<session-id>.jsonl
# - SQLite: ~/.lunaroute/sessions.db
#
# Query sessions:
# sqlite3 ~/.lunaroute/sessions.db "SELECT * FROM sessions ORDER BY created_at DESC LIMIT 10"
#
# Features:
# - Zero-copy passthrough (no normalization overhead)
# - 100% API fidelity (preserves extended thinking)
# - Dual-format recording (JSONL + SQLite)
# - Automatic retention management
# - Session statistics tracking
# - Prometheus metrics at /metrics
