# Production Configuration
# Full-featured setup with session recording and metrics

host: "0.0.0.0"
port: 3000

# API dialect - which format to accept
api_dialect: "anthropic"

providers:
  anthropic:
    enabled: true
    api_key: "${ANTHROPIC_API_KEY}"  # Read from environment

session_recording:
  enabled: true
  sessions_dir: "~/.lunaroute/sessions"

# Session statistics tracking
session_stats_max_sessions: 1000

logging:
  level: "info"
  log_requests: true

# Metrics and health endpoints available at:
# - GET /healthz  (liveness)
# - GET /readyz   (readiness)
# - GET /metrics  (Prometheus)
